import Head from "next/head";
import Link from "next/link";
import footer from "@/components/footer";
import { useState } from "react";
import { addCampaign, getLastCampaignId } from "../services/Web3Service";

export default function Create() {

    const [campaign, setCampaign] = useState({});
    const [message, setMessage] = useState("");

    function onInputChange(evt) {
        setCampaign(prevState => ({ ...prevState, [evt.target.id]: evt.target.value }));
    }

    function btnSaveClick() {
        setMessage("Saving...wait...");
        addCampaign(campaign)
            .then(tx => getLastCampaignId())
            .then(id => setMessage(`Campaign saved with ID <b>${id}</b>. Tell your friends and give them this number.`))
            .catch(err => {
                console.error(err);
                setMessage(err.message);
            })
    }

    return (
        <>
            <Head>
                <title>Donate Crypto | Creates a new campaign</title>
                <meta charSet='utf-8' />
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <div className="container">
                <h1 className="display-5 fw-bold text-body-emphasis lh-1 mb-3">Donate Crypto</h1>
                <p>Fill in the fields to include your campaign on the platform.</p>
                <hr className="mb-4" />
                <div className="col-6">
                    <div className="form-floating mb-3">
                        <input type="text" id="title" className="form-control" value={campaign.title} onChange={onInputChange} />
                        <label for="title">Título:</label>
                    </div>
                    <div className="form-floating mb-3">
                        <textarea id="description" className="form-control" value={campaign.description} onChange={onInputChange} />
                        <label for="description">Description:</label>
                    </div>
                    <div className="form-floating mb-3">
                        <input type="text" id="imageUrl" className="form-control" value={campaign.imageUrl} onChange={onInputChange} />
                        <label for="imageUrl">Image URL:</label>
                    </div>
                    <div className="form-floating mb-3">
                        <input type="text" id="videoUrl" className="form-control" value={campaign.videoUrl} onChange={onInputChange} />
                        <label for="videoUrl">Video URL:</label>
                    </div>
                </div>
                <div className="col-6 mb-3">
                    <input type="button" className="btn btn-primary col-12 p-3" value="Save campaign" onClick={btnSaveClick} />
                </div>
                <div className="col-6 mb-3">
                    <Link href="/" className="btn btn-secondary col-12 p-3">Back</Link>
                </div>
                {
                    message
                        ? <div className="alert alert-success p-3 col-6" role="alert">{message}</div>
                        : <></>
                }
                <footer />
            </div>
        </>
    )
}