import { useState } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import footer from '@/components/footer';
import { doLogin } from '@/services/Web3Service';

export default function Home() {

  const [wallet, setWallet] = useState("");
  const [error, setError] = useState("");

  function btnLoginClick() {
    doLogin()
      .then(wallet => setWallet(wallet))
      .catch(err => setError(err.message));
  }

  return (
    <>
      <Head>
        <title>Donate Crypto | Index</title>
        <meta charSet='utf-8' />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="container px-4 py-5">
        <div className="row flex-lg-row-reverse align-items-center py-5 g-5">
          {
            !wallet
              ? (
                <div className="col-10 col-sm-8 col-lg-6">
                  <img src="/image.png" className="d-block mx-lg-auto img-fluid" width="700" height="500" />
                </div>
              )
              : (
                <div className="col-10 col-sm-8 col-lg-6">
                  <p className='mb-3'>Welcome! {wallet}</p>
                  <p className='mb-3'>What do you wish?</p>
                  <div className='col-12'>
                    <p><Link href="/donate" className='btn btn-primary col-6 p-3'>Donate</Link></p>
                    <p><Link href="/create" className='btn btn-secondary col-6 p-3'>Create a new campaign</Link></p>
                  </div>
                </div>
              )
          }

          <div className="col-lg-6">
            <h1 className="display-5 fw-bold text-body-emphasis lh-1 mb-3">Donate Crypto</h1>
            <p className='lead'>Your decentralized donation platform.</p>
            <p className='lead mb-3'>Login with your wallet, create your campaign or donate to an existing one.</p>
            {
              !wallet
                ? (
                  <div className="d-grid gap-2 d-md-flex justify-content-md-start">
                    <button type='button' className='btn btn-primary btn-lg px-4 me-md-2' onClick={btnLoginClick}>
                      <img src="/metamask.svg" width="64" className="me-3" />
                      Connect to Metamask
                    </button>
                    {
                      error
                        ? <div className="alert alert-danger p-3 col-6" role="alert">{error}</div>
                        : <></>
                    }
                  </div>
                )
                : <></>
            }
          </div>
        </div>
        <footer />
      </div>
    </>
  )
}